$font = JetBrainsMono NF Medium

# Tokyo Night
$background = rgba(1a1b26ff)
$surface = rgb(24283b)
$text = rgb(c0caf5)
$accent = rgb(7aa2f7)
$error = rgb(f7768e)

general {
    hide_cursor = true
    disable_loading_bar = true
    ignore_empty_input = true
}

background {
    monitor =
    color = $background
}

label {
    monitor =
    text = cmd[update:1000] date +"%H:%M"
    color = $text
    font_size = 110
    font_family = $font
    position = 0, 60
    halign = center
    valign = center
}

input-field {
    monitor =
    size = 260, 44
    rounding = 10
    outline_thickness = 2
    outer_color = $accent
    inner_color = $surface
    font_color = $text
    font_family = $font
    check_color = $accent
    fail_color = $error
    fail_text = $FAIL
    placeholder_text =
    dots_size = 0.25
    dots_spacing = 0.3
    dots_center = true
    fade_on_empty = false
    position = 0, -80
    halign = center
    valign = center
}
